version: '2'
services:
  nginx:
    image: judge0/jwilder-nginx-proxy:latest-2020-02-11
    environment:
      - DEFAULT_HOST=judge0.local
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
    restart: always

  server:
    image: judge0/judge0:latest-dev
    environment:
      - VIRTUAL_HOST=judge0.local
    volumes:
      - .:/api
    ports:
      - "3000:3000"
      - "3001:3001" # For ./scripts/dev/serve-docs
    privileged: true

  db:
    image: postgres:13.0
    env_file: judge0.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis:6.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    volumes:
      - redis-data:/data
    restart: always

  resque:
    image: ennexa/resque-web:latest
    entrypoint: ""
    command: [
      "bash", "-c",
      'resque-web -FL -r redis://:$$REDIS_PASSWORD@$$REDIS_HOST:$$REDIS_PORT'
    ]
    env_file: judge0.conf
    ports:
      - "5678:5678"
    restart: always

volumes:
  postgres-data:
  redis-data:
