version: "2"

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100M

x-db: &db
  POSTGRES_HOST: db
  POSTGRES_PORT: 5432
  POSTGRES_DB: judge0
  POSTGRES_USER: judge0
  POSTGRES_PASSWORD: YourPasswordHere1234

x-redis: &redis
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_PASSWORD: YourPasswordHere1234

x-config: &config
  JUDGE0_CONFIGURATION_OPTIONS_HELP: https://github.com/judge0/judge0/blob/master/judge0.conf

services:
  server:
    image: judge0/judge0:latest
    environment:
      <<: *config
      <<: *db
      <<: *redis
    ports:
      - "2358:2358"
    privileged: true
    <<: *logging
    restart: always

  worker:
    image: judge0/judge0:latest
    command: ["./scripts/workers"]
    environment:
      <<: *config
      <<: *db
      <<: *redis
    privileged: true
    <<: *logging
    restart: always

  db:
    image: postgres:13.0
    environment: *db
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    <<: *logging
    restart: always

  redis:
    image: redis:6.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    environment: *redis
    volumes:
      - redis-data:/data
    <<: *logging
    restart: always

volumes:
  postgres-data:
  redis-data:
