version: '2'

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  api:
    image: judge0/api:latest
    volumes:
      - ./judge0-api.conf:/judge0-api.conf:ro
    ports:
      - "80:3000"
    privileged: true
    <<: *default-logging
    restart: always

  worker:
    image: judge0/api:latest
    command: ["./scripts/workers"]
    volumes:
      - ./judge0-api.conf:/judge0-api.conf:ro
    privileged: true
    <<: *default-logging
    restart: always

  db:
    image: postgres:9.6
    env_file: judge0-api.conf
    volumes:
      - ./srv/postgres-data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:4.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0-api.conf
    volumes:
      - ./srv/redis-data:/data
    <<: *default-logging
    restart: always
