version: '2'
services:
  api:
    image: judge0/api
    env_file: judge0-api.conf
    ports:
      - "3000:3000"
    privileged: true
    restart: always

  worker:
    image: judge0/api
    env_file: judge0-api.conf
    command: rails resque:work
    privileged: true
    restart: always

  db:
    image: postgres
    env_file: judge0-api.conf
    volumes:
      - ./srv/postgres-data:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - ./srv/redis-data:/data
    restart: always
