version: '2'
services:
  api:
    image: judge0/api
    volumes:
      - ./judge0-api.conf:/judge0-api.conf:ro
    ports:
      - "3000:3000"
    privileged: true
    restart: always

  worker:
    image: judge0/api
    command: ["./scripts/run-workers"]
    volumes:
      - ./judge0-api.conf:/judge0-api.conf:ro
    privileged: true
    restart: always

  db:
    image: postgres:9.6
    env_file: judge0-api.conf
    volumes:
      - ./srv/postgres-data:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis:4.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0-api.conf
    volumes:
      - ./srv/redis-data:/data
    restart: always
